spring:
  application:
    name: journalApplication
  config:
    import: optional:file:.env[.properties]
  profiles:
    default: local
  jpa:
    open-in-view: false
  data:
    redis:
      repositories:
        enabled: false

logging:
  level:
    root: INFO
    com.darshan.journalApplication: INFO

features:
  sentiment-scheduler: false

weather:
  api:
    key: ${WEATHER_API_KEY:}
